services:
    back:
        container_name: symfony-back
        build:
            context: .
            dockerfile: docker/back/Dockerfile
            args:
                - UID
                - GID
        restart: always
        ports:
            - '81:80'
        volumes:
            - './project/back:/app:cached'
            - './.env:/app/.env'
            - '~/.composer:/.composer'
        networks:
            - mzk-test
        env_file:
            - ./.env
    front:
        container_name: next-front
        build:
            context: .
            dockerfile: docker/front/Dockerfile
            args:
                - UID
                - GID
        restart: always
        ports:
            - '3000:3000'
    db:
        image: mysql:8
        command: ["mysqld", "--mysql-native-password=ON"]
        container_name: mysql-db
        restart: always
        env_file:
            - ./.env
        ports:
            - '3307:3306'
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
        networks:
            - mzk-test
networks:
    mzk-test:
        driver: bridge
